- pyfar/dsp/classes.py
- pyfar/dsp/filter.py
- tests/test_filter_classes.py
Closes #10 
- added comment property to Filter class
- all filters now write comments upon creation
> Filter comment

- pyfar/dsp/classes.py
- pyfar/dsp/filter.py
- tests/test_filter_classes.py
Closes #20 
- Add a sampling rate to the filter
- Check the sampling rate before processing data.
> Add sampling rate to filter class objects

- pyfar/dsp/filter.py
- tests/test_dsp.py
- tests/test_filter.py
Closes #26 
- added tests for filters
- minor bug fixes and typos in filter methods
> Feature testing filters

- tests/test_io_data/generate_test_io_data.py
Closes #41 
- The function generate_test_sofas was called in generate_test_io_data.py. This resulted in a recreation of the test files due to its import in test_io.py, further causing git to indicate them as modified.
> Bugfix: Sofa read test results in modifies files

- tox.ini
Closes #55 
- Add simple unit-testing for example notebooks using the pytest plug-in nbmake
> Test example notbook using the pytest plugin nbmake

- .gitignore
- pyfar/orientations.py
- tests/test_utils.py
Closes #72 
- implementation changes applied to Orientations after scipy.spatial.transform.Rotation has been shipped as Cython
- tests/__init__.py on .gitignore because otherwise test discovery and debug does not work properly
> Hotfix orientations utils

- pyfar/signal.py
- tests/test_signal.py
Closes #63 
- added flatten and reshape methods for signal
- added test for new methods
> added flatten and reshape method for signal

- tests/test_coordinates.py
> Remove deprecated comments and interactive cells from test_coordinates

- pyfar/spatial/spatial.py
- tests/conftest.py
- tests/test_utils.py
I guess we don't need copy-Methods in all classes. Just those belonging to the public interface, not?
> sphericalvoronoi.copy() implemented.

- pyfar/signal.py
- tests/test_signal.py
Closes #89 
- remove the setter and test for `Signal.signal_type`
> Remove the setter and test for Signal.signal_type

- pyfar/signal.py
As discussed in the weekly. You can already review. I will merge this after #86
> update documentation for arithmetic operations

- pyfar/plot/shortcuts/shortcuts.json
- pyfar/plot/utils.py
We discussed that we want to have more verbose shortcuts and support a better support for the American keyboard layout in the weekly. Please add the shortcuts you want to `plots/shortcuts/shortcuts.json`. Make sure to not shadow shortcuts from matplotlib: https://matplotlib.org/3.1.1/users/navigation_toolbar.html
- add more shortcuts to `plots/shortcuts/shortcuts.json`
- improve display of `plots.utils.shortcuts`
> Added more verbose shortcuts and improved display of shortcuts

- tests/conftest.py
- tests/test_frequency_data.py
- tests/test_time_data.py
- tests/test_utils.py
This is a **really small pull request** that implements things taht are used by the following feature/save-timedata-frequencydata, but actually not part of the feature itself.
> Added tests and fixtures for TimeData and FrequencyData.

- MANIFEST.in
Closes #110 
- Add missing non-source files to Manifest
> Add missing non-source files to manifest

- pyfar/spatial/external/__init__.py
- pyfar/spatial/samplings.py
Closes #112 
- Fix import of external submodule in samplings
> Fix broken import of external samplings

- pyfar/dsp/dsp.py
- tests/test_dsp.py
- Add a faster method to calculate the group delay.
- Make the new version the default version
> Faster group delay calculation

- pyfar/plot/utils.py
Updated the docstring of `plot.utils.shortcuts()`
> updated docstring with new short cuts

- pyfar/spatial/samplings.py
Closes #118
- switch and invert Fliege-Maier Sampling points for consistency (see #188)
> Updated Fliege-Maier samplings for consitency

- pyfar/coordinates.py
- tests/test_coordinates.py
Closes #122 
- New Coordinates object is returned by calling self.copy()
- Added test
> Coordinates __getitem__ bugfix

- requirements_dev.txt
- tox.ini
Closes #117 
- Build wheel binaries using CI
- Run all tests against wheels
- (Source distributions are already tested via tox)
> Run CI against wheel binaries

- README.rst
- docs/modules.rst
- docs/pyfar.io.rst
- pyfar/io.py
- setup.py
As discussed during the weekly.
> Add info@pyfar and pyfar.org

- CONTRIBUTING.rst
Micro-change to CONTRIBUTING.rst, see #93
> flake8 rules added to CONTRIBUTING.rst, closes #93

- CONTRIBUTING.rst
We can check and edit this, as we revisit the pyfar documentation.
> Added documentation guidelines

- pyfar/signals/deterministic.py
- tests/test_signals.py
As discussed during the weekly
- changed normalization
- adjusted tests
- re-inspected and re-calculated references in tests/references
> changed fft normalization of sweep signals to none

- docs/modules.rst
- docs/pyfar.samplings.rst
- docs/pyfar.spatial.samplings.rst
- pyfar/samplings/__init__.py
- pyfar/samplings/samplings.py
- pyfar/samplings/spatial.py
I suggest that you check the documentation in the html version after building it (see CONTRIBUTIONS.rst). Feel free to directly commit fixes for typos and minor issues.
> Documentation pyfar.samplings

- README.rst
- Update the mybinder link of the example notebook to the main branch
> update exmple nb binder link to main branch

- docs/conf.py
- docs/pyfar.classes_audio.rst
- docs/pyfar.classes_coordinates.rst
- docs/pyfar.classes_filter.rst
- docs/pyfar.classes_orientations.rst
- pyfar/classes/audio.py
- pyfar/classes/coordinates.py
- pyfar/classes/orientations.py
- pyfar/dsp/__init__.py
Update docstrings to new class structure
> Docs classes

- pyfar/plot/_interaction.py
- pyfar/plot/_line.py
- tests/test_coordinates.py
- tests/test_interaction.py
- tests/test_plot.py
Closes #116
There are two things I did apart from adding tests for interaction
- added the private functions `_get_new_axis_limits` to `plot._interaction` and `_get_quad_mesh_from_axis` to `plot._line`. This is not new functionality. I moved code into functions for ease of testing and better re-usability
- Some tests only failed if other tests preceded them. I added a few `plt.close("all")` to avoid this.
> Add testing for interaction

- pyfar/dsp/fft.py
None, general improvement in the documentation.
- fix inline math
- fix references
- improve docstring of the module and fft.normalization
Note: I think the test failed due to a connection time out on travis. Code should be fine. We can re-run the test before we push...
> Improve documentation for dsp.fft

- pyfar/dsp/__init__.py
- pyfar/dsp/dsp.py
- tests/test_dsp.py
Closes nothing
Add zero phase signal generation and testing.
> Introduce zero phase signal generation

- pyfar/dsp/__init__.py
- pyfar/dsp/dsp.py
- tests/test_dsp.py
Nothing
- add function and testing for linear phase signal generation
> Linear phase signal generation

- pyfar/classes/filter.py
Related to #88 
The function applying a filter to input data is no longer stored as handle, but handled through a static class method.
This should result in filter objects that can be saved using the pyfar i/o routines
> Improved filter processing

- tests/test_fractional_octaves.py
Closes #127 
- Replace the mock with a signal
> Replace the mock in the fractional octave test

- AUTHORS.rst
- HISTORY.rst
> Complete contributors and history

- examples/pyfar_demo.ipynb
- pyfar/__init__.py
- pyfar/classes/audio.py
- pyfar/dsp/dsp.py
- setup.cfg
- setup.py
- tests/test_dsp_interpolate_spectrum.py
- tests/test_frequency_data.py
- tests/test_signal_arithmetic.py
Closes #223
- Only allow `'none'` FFT normalization for `FrequencyData` objects
- Update test and documentation
- Change default norm from `None` to `'none'`. This is more explicit and `None` was converted to `'non'` internally anyhow.
> Bug fix/frequency data fft norm

- CONTRIBUTING.rst
Make pyfar more open to new developers by
- Improve installation guide lines for developers
- remove recommendation for using tox (we do not really do it and it might be even more intimidating for new people)
Creating a new environment with the new guidelines worked fine for me. Can you test as well?
> Improve contribution guide lines

- pyfar/classes/audio.py
- tests/test_signal_arithmetic.py
Closes #224 
- added `_match_fft_norm` to `_assert_match_for_arithmetics`
- updated tests accordingly
> add `_match_fft_norm` to audio arithmetics

- AUTHORS.rst
- CONTRIBUTING.rst
Nothing
Minor improvements in contributing guide-lines
> Enhancement: contributing

- pyfar/plot/_utils.py
Can anyone explain why this Closes #278 
- moved default argument from function definition to function body
> Pyfar import returns empty figure

- HISTORY.rst
- Update History.rst for release of pyfar 0.4.0
> Prepare release of pyfar 0.4.0

- pyfar/classes/orientations.py
- pyfar/dsp/dsp.py
- tests/test_io.py
Fix or catch deprecation warning for
- numpy data types
- numpy array creation
- deprecated scipy window function
> Fix several deprecation warnings

- HISTORY.rst
- pyfar/plot/_two_d.py
- pyfar/plot/_utils.py
- tests/test_plot__utils.py
Closes #290 
- add assertion for `shading='flat'`
- fix assertion for data type
- add missing tests
> Bugfix for 2D plots

- pyfar/_concepts/arithmetic_operations.py
- pyfar/classes/audio.py
Closes #320 
Update outdated docstrings of arithmetic functions
> Documentation of arithmetic operations

- pyfar/io/_codec.py
Improve developer documentation for adding read/write support to pyfar objects.
Note that the docstring references a function that is not merged into develop yet: https://github.com/pyfar/pyfar/blob/feature/auditory_filters/pyfar/dsp/filter/gammatone.py
> Improve developer documentation

- pyfar/io/io.py
> Bugfix exception catching for soundfile import

- pyfar/classes/audio.py
no one: 
- fixes type in doc for FreqencyData for default type
> fixed type in FrequencyData for default type complex

- docs/conf.py
Explicitly set the language in the Sphinx configuration.
> Explicitly set sphinx language

- pyfar/_concepts/audio_classes.py
- fix typos in audio classes doc
> fix typos in audio classes doc

- pyfar/dsp/filter/gammatone.py
- pyfar/dsp/interpolation.py
Closes #349 
- fix bug
- be happy
> fix bugs in documentation

- pyfar/dsp/dsp.py
- tests/test_dsp_deconvolution.py
Suggested changes from mberz applied to #368
> add freq_range kwarg to deconvolve

- AUTHORS.rst
- HISTORY.rst
> Update for 0.5.0 release

- pyfar/dsp/filter/gammatone.py
- tests/test_filter_gammatone.py
Closes #373
- add support for arbitrary sampling rates
> Fix sampling rate in Gammatone filter bank

- setup.py
Closes #356 
Update the urls on pypi
> update urls for the project, code repo and docs

- pyfar/dsp/dsp.py
- pyfar/samplings/samplings.py
- pyfar/signals/files.py
- tests/test_filter_shelve_cascade.py
- tests/test_plot_interaction.py
- tests/test_signals.py
> Fix more warnings in tests

- pyfar/signals/files.py
- tests/test_signals_files.py
Closes #383. Changes in Coordinates are from #386 
- Use indices instead of masks to get HRIRs.
- Test order of returned HRIRs
> Return HRIRs in requested order

- pyfar/_concepts/audio_classes.py
- pyfar/dsp/dsp.py
- tests/test_dsp.py
Closes #382 
- add cdim handling to dsp.convolve
- add testing thereof
- add cdim to audio concept documentation because cdim is now mentioned in the docstring of dsp.convolve
> Handle signals with different cdims in dsp.convolve

- pyfar/io/io.py
- tests/conftest.py
- tests/test_io.py
Closes #410, fails due to #409
- reshape data prior to generating pyfar audio objects
- update documentation
- update testing
> Reading Sofa files of type FIR-E and TF-E

- pyfar/dsp/dsp.py
- tests/test_dsp_average.py
In #399 we decided
- that we also allow NaNs in dsp.average function
> NaNs in dsp.average

- pyfar/classes/coordinates.py
- pyfar/signals/files.py
- tests/test_coordinates.py
- tests/test_signals_files.py
Closes #383 
This PR consists of cherry-picks of the bugfixes introduced in PRs #387 and #386
> Hotfix: Return HRIRs in requested order

- pyfar/dsp/filter/fractional_octaves.py
> Update docstring of `pyfar.dsp.fractional_octava_bands`

- .circleci/config.yml
- setup.py
- tox.ini
> add python 3.11

- pyfar/classes/coordinates.py
- pyfar/dsp/dsp.py
- pyfar/plot/_utils.py
- tests/test_dsp.py
- tests/test_plot_interaction.py
Cherry pick the content of #483 for the main branch
> fix flake 8 revisited

- pyfar/classes/coordinates.py
> yet another flake8 fix

- pyfar/classes/filter.py
Closes #466 
- Add the `@property` decorator
- Return 2* number of SOS sections as filter order
> Bugfix property decorator FilterSOS order

- requirements_dev.txt
- setup.py
- tests/test_io.py
> update sofar version

- pyfar/plot/_utils.py
- pyfar/plot/line.py
- pyfar/plot/two_d.py
- tests/test_deprecations.py
- Removed all code that will be deprecated in pyfar 0.6.0
- Locally tested the deprecations by bumping the version to 0.6.0
> Deprecations for Pyfar 0.6.0

- pyfar/__init__.py
- pyfar/classes/coordinates.py
- tests/test_coordinates_new.py
Closes #432
will add testing if we agree on the general behavior and functionality
> Add `rad2deg` and `deg2rad`

- pyfar/classes/audio.py
- tests/test_audio_signal_arithmetic.py
tiny bugfix in _get_arithmetic_data
* exchange `isinstance ` with check for type. 
add tests for multiplication in frequency domain
* multiplication in time domain didn't evoke the error
> Complex audio arithmetics

- .circleci/config.yml
- tests/test_audio_frequency_data.py
- tests/test_audio_signal.py
- tests/test_audio_time_data.py
- add tests folder to flake8 test
- fix flake8 errors in tests
> Enhance flake8 testing

- pyfar/classes/coordinates.py
- tests/test_coordinates_find.py
Closes #523
- fix bug and replace ``==`` to ``in``
- add test for spherical distance measure
- add doc and test for atol
- add new option ``radius_tol`` to change the tolerance for radius + add test
> hotfix find_within

- CONTRIBUTING.rst
- add suggestions by @pingelit https://github.com/pyfar/cookiecutter-pypackage/pull/4 
-
-
> fix english in doc

- .circleci/config.yml
- setup.py
-    add test for python 3.12 on circle ci
-    add tag for 3.12 support
> Add support for python 3.12

- pyfar/dsp/dsp.py
- tests/conftest.py
- tests/test_dsp.py
Closes #384
- edit group delay to work with complex signals
> Complex group delay

- pyfar/utils.py
- tests/test_utils.py
Closes #
- test concatenation of complex signals
> Test complex concatenate

- .github/workflows/create_issue_if_coockiecutter.yml
if a PR with tag ``'cookiecutter'`` to is merged an automatic issue is created in [cookiecutter-pypackage](https://github.com/pyfar/cookiecutter-pypackage)
here is the example:
https://github.com/pyfar/cookiecutter-pypackage/issues/18
discussion:
- the exanct content of the issue
> Github Action: if PR with tag 'cookiecutter' is merged, it will create an issue in cookiecutter-pypackage

- pyfar/classes/audio.py
- tests/test_audio_signal.py
Closes #
- bugfix pass wrong even/odd flag in complex setter
-
-
> Bugfix set complex freq

- tests/test_dsp_deconvolution.py
> Complex deconvolution

- pyfar/_concepts/plots.py
- pyfar/classes/audio.py
- pyfar/dsp/dsp.py
- pyfar/dsp/interpolation.py
- pyfar/signals/deterministic.py
- pyfar/utils.py
- let sphinx create the links to other docs
- more stable, avoiding dead links
- throws a warning it the link is not correct.
- result in doc should be the same as before
> use intersphinx for numpy and matplotlib absolute links

- pyfar/_utils.py
Fix broken docstrings of decorated functions introduced in #589.
Closes #604
> fix broken docstring of decorated functions

- tests/test_dsp_interpolation.py
> Test complex frac time shift

- pyfar/classes/audio.py
- tests/test_audio_signal.py
Closes #602 
Added cdim property to audio classes
> add cdim property to audio classes

- pyfar/io/io.py
> Enhance user warning for writing clipped audio files

- docs/conf.py
- pyfar/classes/audio.py
- pyfar/classes/coordinates.py
- pyfar/classes/filter.py
- pyfar/classes/orientations.py
- pyfar/dsp/dsp.py
- pyfar/dsp/filter/band_filter.py
- pyfar/dsp/filter/gammatone.py
- pyfar/dsp/interpolation.py
- pyfar/io/_codec.py
- pyfar/io/io.py
- pyfar/plot/_two_d.py
- pyfar/plot/_utils.py
- pyfar/plot/line.py
- pyfar/plot/spatial.py
- pyfar/plot/two_d.py
- pyfar/plot/utils.py
- pyfar/samplings/spatial.py
fix and add intersphinx references
add references where it make scence
mainly for the numpy, scipy and matplotlib
gallery was already done
> fix and add intersphinx references and other references

- pyfar/dsp/filter/audiofilter.py
> Fix cascaded shelving docstring

- pyfar/dsp/filter/fractional_octaves.py
> Fix erroneous default mentioned in docstring

- pyfar/dsp/dsp.py
- tests/test_dsp_normalize.py
> Fix dsp normalize

- pyfar/classes/audio.py
- tests/test_audio_signal_iterator.py
> update signal iterator

- pyfar/signals/deterministic.py
- tests/test_signals.py
- pf.signals.impulse(3, 0, np.ones((1,1)) was not working
- bug is fixed and tests are added
> allow pf.signals.impulse(3, 0, np.ones((1,1))

- pyfar/classes/audio.py
- tests/test_audio_signal.py
- tests/test_audio_time_data.py
> implement _return_item for complex signals

- pyfar/plot/two_d.py
- tests/test_plot__utils.py
> add side parameter to phase_2d

- pyfar/dsp/interpolation.py
- tests/test_dsp_interpolation.py
> don't allow fractional octave smoothing for complex signals

- pyfar/classes/coordinates.py
- tests/test_coordinates.py
same problem as in #664, but in the coordiantes class
we could think to shift the match_shape into the utils, so that we can use it anywhere
> let numpy handle the broadcasting in Coordinates

- tests/test_filter.py
- Fix tests after merging the new squeeze behavior from main into develop
> update for new squeeze behavior in dsp

- pyproject.toml
> ruff: FIX Code should not contain FIXME, TODO, etc.

- pyfar/classes/__init__.py
- pyfar/classes/coordinates.py
- pyfar/dsp/__init__.py
- pyfar/dsp/dsp.py
- pyfar/dsp/filter/__init__.py
- pyfar/io/io.py
- pyfar/plot/__init__.py
- pyfar/plot/ticker.py
- pyfar/testing/stub_utils.py
- pyproject.toml
- tests/test_coordinates.py
- tests/test_coordinates_find.py
- tests/test_dsp_average.py
- tests/test_dsp_interpolation.py
- tests/test_fft.py
- tests/test_filter_classes.py
- tests/test_filter_gammatone.py
- tests/test_io.py
- tests/test_io_comsol.py
- tests/test_plot.py
- tests/test_plot_interaction.py
- tests/test_signals.py
- tests/test_signals_files.py
> Ruff: COM, trailing comma rules

- pyfar/testing/stub_utils.py
- pyproject.toml
- tests/conftest.py
- tests/test_audio_frequency_data.py
- tests/test_audio_signal.py
- tests/test_audio_time_data.py
- tests/test_dsp.py
- tests/test_spatial.py
See #647
- the only rule we did not follow was about the random stuff
- should we really use random in tests?
> Ruff: NPY Check all numpy related deprecations

- pyfar/classes/audio.py
- pyfar/classes/coordinates.py
- pyfar/classes/orientations.py
- pyfar/dsp/filter/_audiofilter.py
- pyfar/dsp/filter/audiofilter.py
- pyfar/dsp/interpolation.py
- pyfar/samplings/external/eq_area_partitions.py
- pyproject.toml
- tests/test_coordinates.py
- tests/test_coordinates_new.py
- tests/test_copy.py
- tests/test_dsp.py
> ruff: ERA no commented code

- pyfar/classes/filter.py
- pyfar/dsp/interpolation.py
- pyfar/io/io.py
- pyfar/testing/stub_utils.py
- pyproject.toml
- tests/conftest.py
- tests/test_coordinates_new.py
- tests/test_deprecations.py
- tests/test_dsp.py
- tests/test_dsp_interpolation.py
- tests/test_filter_classes.py
- tests/test_filter_gammatone.py
- tests/test_io.py
- tests/test_io_comsol.py
See #647
- apply for internal use
- how ro proceed with audio_subtypes and default_audio_subtype?
> Ruff: A, Avoid builtin function and type shadowing.

- pyfar/__init__.py
- pyfar/classes/coordinates.py
- tests/test_coordiantes_arithmetic.py
> add arithmetics for coordinates

- pyfar/classes/transmission_matrix.py
related to Transmission Matrix
> fix typo and parameter properties in Transmission Matrix

- pyfar/io/_codec.py
> Update internal documentation for _codec module

- pyfar/dsp/filter/band_filter.py
- requirements_dev.txt
- setup.py
https://github.com/pyfar/gallery/issues/77
> allow sphinx 8

- .circleci/config.yml
- setup.py
to install locally:
`conda create --name pyfar python=3.13.0rc2 conda-forge/label/python_rc::_python_rc --channel conda-forge --override-channels`
> Python 3.13 support

- pyfar/dsp/__init__.py
- pyfar/dsp/dsp.py
- pyfar/signals/deterministic.py
- tests/test_dsp_correlate.py
Was merged into main by mistake in #713. Now merging into dev
> Feature: correlate

- pyfar/dsp/dsp.py
Add to the doc what has already been done in the code.
> dsp.time_shift: add broadcastable and array_like to doc (shift)

- pyfar/dsp/__init__.py
> bugfix from merge main into dev

- pyfar/plot/_interaction.py
> fix bug from matplotlib 3.10

- pyfar/dsp/dsp.py
- tests/test_dsp.py
return int array for find_impulse_response_start() as highlighted in the docs
since they return index the type should be int.
> HOT: return int array for find_impulse_response_start() 

- pyfar/dsp/dsp.py
- tests/test_deprecations.py
> Remove deprecated parameters in pf.dsp.pad_zero

- pyfar/dsp/dsp.py
- pyfar/dsp/filter/fractional_octaves.py
- pyfar/dsp/filter/gammatone.py
- pyfar/io/io.py
- tests/test_deprecations.py
- tests/test_dsp_deconvolution.py
- tests/test_filter_gammatone.py
- tests/test_signals.py
> remove deprecated freq_range parameter

- pyfar/classes/audio.py
- tests/test_deprecations.py
replaces #744 this pr merges in develop directly
see  #747
> remove deprecated len(pf.Signal)

- .github/workflows/has_label.yml
- .github/workflows/has_version_milestone.yml
if we rmove the version labels all tests are failing, so my idea was to replace it by a check for any label (eg related by topic or type).
an alternative apporach would be to just remove the test
> HOT: replace version label check by check for any label

- pyfar/classes/filter.py
- tests/test_filter_classes.py
Closes #749
- add `impulse_response` method to `pyfar.Filter` class
- add testing thereof
> Filter impulse response

- pyfar/classes/audio.py
- pyfar/classes/transmission_matrix.py
None
I just fixed two typos I noticed while experimenting.
> Fixed some typos

- pyfar/constants/__init__.py
- pyfar/constants/speed_of_sound.py
- tests/test_constants_speed_of_sound.py
> speed of sound ideal gas law

- pyfar/classes/filter.py
- tests/test_filter_classes.py
Add setter for filter state property
Closes #757
> Add filter state setter

- pyfar/dsp/dsp.py
- tests/test_dsp.py
Closes #775 
- Add if case for catching the bug
- Add test for the critical case.
The new test failed before changing `find_impulse_response_dealy`, indicating that the suggested change fixes the bug.
> hot fix for crash in dsp.find_impulse_response_delay

- HISTORY.rst
Update history. Bumpversion will follow...
> update for release v0.7.2

- pyfar/constants/__init__.py
- pyfar/constants/constants.py
- pyfar/constants/speed_of_sound.py
- pyfar/constants/utils.py
- tests/test_constants_speed_of_sound.py
- tests/test_constants_utils.py
Contributes to #428
- introduces magnus formula for saturation vapour pressure
- implement ideal gas speed of sound calculation using magnus Formula
- uses the new constants
> Reopen: Speed of sound ideal gas

- docs/conf.py
apply latest cookiecutter
- fix heading with packages dropdown see https://pyfar--789.org.readthedocs.build/en/789/pyfar.html (https://github.com/pyfar/cookiecutter-pypackage/pull/46)
- restructure auto downlaod from gallery https://github.com/pyfar/cookiecutter-pypackage/pull/41
> apply cookiecutter

- pyfar/classes/coordinates.py
Very similar to  #804, but for the Coordinates._set_weights() method
- move weights checks from ``_set_weights`` into a dedicated method which just do the input checks called ``_check_weights``
- does not change the behaviour of Coordinates
>  Patch: Coordinates._set_weights: separate internal checks from setting the variables

- HISTORY.rst
> Update history for 0.7.3 release

- pyproject.toml
changes description to 
Python package for acoustics research
> hot: fix description of pyfar in pyproject.toml
