pyfar/pyfar

pyfar/dsp/dsp.py
tests/test_dsp.py
tests/test_plot.py

Closes #29 
- use scipy.signal.group_delay instead of manual phase derivative

fixed bug in group delay calculation

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/assign_to_project.yml

Closes #12 
added wokflow that will
- assign a new issue/pull-request to *Code Backlog* if labeled bug, dependencies, documentation, duplicate, enhancement, feature, or hot
- assign a new issue/pull-request to *General* if labeled question
Tested on a private repo - worked like a charm. If a new issue/pull-request is opened, the workflow's status is shown at https://github.com/pyfar/pyfar/actions. Once this finished, the issue/pull-request is assigned to the project.

added workflow for automatic project assignment

---

requirements_dev.txt
setup.py

Closes  #11 
- replace the deprecated bump version dependency

replace bumpversion by bump2version in requirements

---

.readthedocs.yml
docs/conf.py

Closes #28 
Use ReadTheDocs.org to build and host the sphinx documentation.
The docs for the pull request branch are found here: https://pyfar.readthedocs.io/en/feature-readthedocs/

Docs hosting on readthedocs

---

pyfar/signal.py

Closes nothing
- add fft_norm to signal.__getitem__

fft_norm was not passed in signal.__getitem__

---

pyfar/dsp/filter.py
pyfar/spatial/samplings.py

Closes #51 
- Replace private submodules without a `__init__.py` with a local import

local import of external sampling submodule in spatial

---

pyfar/testing/__init__.py
pyfar/testing/stub_utils.py
tests/conftest.py
tests/test_stub_utils.py

**Make `stub_utils.py` accessible from other packages.**
Other packages, for example the room acoustic package, also work with pyfar objects and thus require stubs of the pyfar objects for testing. It is thus desired, to make the stub utils from pyfar available to other packages.
- added module `pyfar.testing` which contains `stub_utils.py`
**Note:** Do not check the code in `pyfar/testing/stub_utils.py` during the review. The content is identical to the old `tests/stub_utils.py` (Only docstring added)

moved stub_utils

---

pyfar/coordinates.py
pyfar/dsp/classes.py
pyfar/orientations.py
pyfar/signal.py
pyfar/spatial/spatial.py
requirements_dev.txt
setup.py
tests/conftest.py
tests/test_coordinates.py
tests/test_filter_classes.py
tests/test_orientations.py
tests/test_signal.py
tests/test_spatial.py
tests/test_utils.py

Every public class has now the `__eq__(self)`-method. This enables comparison with `actual == other`. Deepdiff has been chosen because it compares recursivly, shows differences if present and has some nice ignore -features. Moreover it seems to be very stable and is very well supported.
Two tests in test_signal are deliberately not passing. `SignalIterator` seems to have an infinite recursion problem.

Implemented equality checks with deepdiff

---

pyfar/_codec.py
pyfar/dsp/filter.py
pyfar/plot/ticker.py
pyfar/signal.py
pyfar/spatial/external/eq_area_partitions.py
pyfar/spatial/samplings.py
pyfar/testing/stub_utils.py
tests/test_eq_area_partitions.py
tests/test_stub_utils.py

Closes #103 
Replace deprecated numpy aliases of types by builtins. For a full list of deprecated types see the numpy release notes [here](https://numpy.org/devdocs/release/1.20.0-notes.html).

Replace deprecated numpy types by builtins

---

setup.py

As discussed during the weekly
- Restrict python version to >=3.8,<3.9 in setup.py
I've tested this using `pip install -e path/to/my/local/pyfar` and it worked as expected. I get
ERROR: Package 'pyfar' requires a different Python: 3.9.2 not in '<3.9,>=3.7'
and
ERROR: Package 'pyfar' requires a different Python: 3.6.13 not in '<3.9,>=3.7'
when installing pyfar in environments with out of range python versions.
Everything works fine if for python 3.7 and 3.8.

restricted range of python version

---

pyfar/dsp/classes.py
tests/test_filter_classes.py

Closes #144 & #33 
- The `process` method of `Filter` objects iterates all channels
- If a `Filter` has more than one channel, a new dimension is added to the processed `Signal`
- Removed the empty state warning

Bugfix for ignored channels during processing of multi-channel signals in filter classes

---

docs/pyfar.classes_audio.rst
pyfar/signal.py
tests/test_frequency_data.py
tests/test_signal.py
tests/test_time_data.py

I suggest that you check the documentation in the html version after building it (see CONTRIBUTIONS.rst). Feel free to directly commit fixes for typos and minor issues.
I included inherited methods in the documentation and added documentation for magic methods `__iter__`, `__getitem__`, and `__setitem__`.
I touched one thing not related to the documentation
- made SignalIterator a private class

Documentation for audio classes

---

pyfar/io.py

I suggest that you check the documentation in the html version after building it (see CONTRIBUTIONS.rst). Feel free to directly commit fixes for typos and minor issues.
Touched one thing not related to the documentation: replaced to .far suffix check in read() and write with `pathlib.Path(filename).with_suffix('.far')`, this also allows pathlib.Path objects as input.

Read the docs/io

---

pyfar/io.py

I suggest that you check the documentation in the html version after building it (see CONTRIBUTIONS.rst). Feel free to directly commit fixes for typos and minor issues.
Extension to #143

Documentation for pyfar.io

---

MANIFEST.in

- Update MANIFEST.in to new folder of external samplings

Fix wrong path for external sampiling *.mat files

---

pyfar/plot/_interaction.py
pyfar/plot/line.py
pyfar/plot/shortcuts/shortcuts.json

None, general improvement
The shortcuts contained the keyword 'line'. I initially added this because I thought we would have different plots with the same name in sub-modules of plot. We do not have this and all plots are available to the user as plot.name and not plot.line.name. However the keyword line shows up in the shortcuts printed by `pyfar.plot.shortcuts()`, which will be confusing for the users.
- removed occurrences line. wherever it was related to shortcuts

Remove keyword 'line' from shortcuts

---

pyfar/classes/coordinates.py
pyfar/classes/filter.py
pyfar/classes/orientations.py
pyfar/dsp/filter.py

Closes #166
change `import pyfar` to `import pyfar as pf` everywhere. The links were broken due to a bug in Sphinx. I could find the workaround with the help of Chilipp from autodocsumm, who also was so kind to make a detailed issue at Sphinx: https://github.com/sphinx-doc/sphinx/issues/9069

Fix broken links in doc summary tables generated by autodocsumm

---

pyfar/plot/spatial.py

fixes warning starting with Matplotlib 3.4.1:
```
\pyfar\plot\spatial.py:123: MatplotlibDeprecationWarning: Calling gca() with keyword arguments was deprecated in Matplotlib 3.4. Starting two minor releases later, gca() will take no keyword arguments. The gca() function should only be used to get the current axes, or if no axes exist, create new axes with default keyword arguments. To create a new axes with non-default arguments, use plt.axes() or plt.subplot().
```
- used `pyplt.axes` to create axis instead of `pyplot.gca`

Fix Matplotlib deprecated warning for scatter plot

---

pyfar/classes/coordinates.py
tests/test_coordinates.py

- Unified use of numpy testing
- Removed tests that were not needed
- Added parameterization for one case
- Minor bugdixes:
- `Coordinates.get_cyl()` did not convert to degrees
- ValueError was not raised in `Coordinates.get_slice()` if a non existing coordinate was passed
- `Coordinates.__getitem__` did not maintain the correct shape of the coordinate points if only one coordinate was left

Revise testing for coordinates

---

tests/conftest.py
tests/test_fft.py

Use pytest parametrize to run fft test with multiple monkey-patches without writing separate tests.

Use parametrization for fft tests

---

docs/conf.py
pyfar/classes/audio.py
pyfar/classes/coordinates.py
pyfar/dsp/dsp.py
pyfar/dsp/fft.py
pyfar/dsp/filter.py
pyfar/plot/__init__.py
pyfar/plot/_interaction.py
pyfar/plot/line.py
pyfar/plot/utils.py

Closes #179
- add option to include code from plots in the docstrings and removed redundant code (see #179)
- unified import of pyfar in the docstring examples to `import pyfar as pf`

Automatically include code from plots in the documentation

---

tox.ini

Closes #213 
- require nbmake>=0.7.0

Set required nbmake version

---

pyfar/__init__.py
tests/test_signal_arithmetic.py

Arithmetic functions were hard to use and only available from `pyfar.classes.audio.add`. This makes them available as `pyfar.add`
- add imports
- use new import syntax in tests

import arithmetic functions to pyfar

---

.travis.yml
pyfar/dsp/fft.py
requirements_dev.txt
setup.cfg
setup.py
tests/conftest.py
tests/test_dsp.py
tests/test_fft.py
tox.ini

Closes #129 
- Remove pyfftw in favor of scipy fft
- Remove requirement of python < 3.9
I propose to do a patch release after this has been merged.

Remove pyfftw and allow python=3.9

---

pyfar/plot/_line.py

`pyfar.plot.custom_subplot` does not return axes handle
Return axes handle

Return axes handle in custom_subplots

---

pyfar/plot/ticker.py

Plot functions label negative frequencies with positive values, e.g., the label of '-100' Hz is '100'.
- Allow negative frequencies in the LogFormatter that is used to format frequency axis
Signals do not need this, but Frequency data could contain negative frequencies in case of analytical spectra.
I locally tested if this changes anything in the default behavior setting `compare = True` in *tests/test_plot.py* and everything was fine. Is there any reason for not allowing negative values?

allow negative frequencies in LogFormatter

---

pyfar/io/io.py
requirements_dev.txt
setup.py
tests/conftest.py
tests/test_io.py

- Use sofar for reading SOFA files
- Extend DataTypes that can be read for Transfer Functions
- Remove tests for checking the validity of SOFA files in pyfar. This is taken care of by sofar

Refactor pyfar.io.read_sofa

---

pyfar/dsp/dsp.py
tests/test_dsp.py

Closes #242 
- A ``return_ window`` parameter is added to `pyfar.dsp.time_window` to optionally inspect to time window. This is easier than calling the function with ones.

Add return_window parameter to time_window

---

.readthedocs.yml
requirements_dev.txt

Closes #246 
Add sofar and soundfile + dependencies to the requirements_dev file for readthedocs and ci as well to work properly in cases where the pyfar  package itself is not installed or the libsndfile dependency is missing.
Working docs are found here:
https://pyfar.readthedocs.io/en/bugfix-missing_sofar/modules/pyfar.dsp.html

Bugfix: Add missing sofar and soundfike dependencies to requirements and rtd config

---

pyfar/classes/audio.py
tests/test_signal_arithmetic.py

Closes #224 contributes to #244 
- check `fft_norm` in cases like `1 / signal`
- additional tests not required. Case was already tested, but now the behavior is different, e.g., `1 / pf.signals.sine(100, 100)` is not possible anymore

Complete rules for arithmetics

---

pyfar/dsp/dsp.py
pyfar/plot/_two_d.py
tests/test_dsp_spectrogram.py

Closes #257 
- Remove dB parameters from `dsp.spectrogram` and tests thereof
- Move dB parameters to `plot.spectrogram`
- No additional tests of `plot.spectrogram` needed. Parameter tested in `test_plot.py::test_line_dB_option`

dB Parameters in dsp.spectrogram

---

tests/test_io.py

For some audio formats a separate hidden file called `C._t` is created when writing/reading files (see Q13 at https://libsndfile.github.io/libsndfile/FAQ.html). The corresponding tests are extended to remove the file, so is not recognized as new file by Git every time the tests are run.

Bugfix/remove C._t file from tests

---

pyfar/dsp/filter.py

- add missing part of docstring for `pyfar.dsp.filter.high_shelve`

complete docstring

---

pyfar/signals/deterministic.py
tests/test_signals.py

The parameters for the functions `pyfar.signals.impulse` and `pyfar.signals.sine` had to be scalars or of the same shape. Now any parameters that can be broadcasted to the same shape can be passed. This is more flexible, maintains backwards compatibility, and made the code shorter and easier to read.
- added new parameter handling
- added new tests

Enhancement: signals parameters

---

pyfar/dsp/interpolation.py
tests/test_dsp_resample.py

The default for `match_amplitude` should be `'auto'` but was `'time'`.

Fix wrong default value for resample function

---

pyfar/_concepts/arithmetic_operations.py
pyfar/classes/audio.py
tests/test_signal_arithmetic.py

Closes #317
- clarifies arithmetic operations including arrays and audio objects by implementing broadcasting rules
- fixed error for overloaded operators in operations, where the array is first
- add tests for both
- updated docs and concepts

Array broadcasting in arithmetic operations

---

pyfar/dsp/dsp.py
tests/test_dsp_decibel.py

New Parameter 'prefix_return' in dB function.
Default False will do nothing.
Set True and the function will also return 'log_prefix'.
Added, because it is used in two functions currently being developed in branches (normalization and soft limiting)

Insert prefix_return in dB function

---

environment.yml

Closes #337 
- Add a specific and complete enviroment.yml for mybinder to install non python packages via conda.
- This PR does not require a new version of pyfar, as it only affects running the example notebook on mybinder.org
The mybinder.org link for this branch is found here:
https://mybinder.org/v2/gh/pyfar/pyfar/bugfix/libsndfile_mybinder?filepath=examples%2Fpyfar_demo.ipynb
Setting up can take a bit longer due to the custom conda environment. There's also options to use apt, but I'm expecting that this will result in similar setup times. Using the conda environment is more accessible to non-unix users.

Add environment.yml for mybinder.org.

---

.circleci/config.yml

Closes #314 
Test building the Sphinx documentation
This will not check if the generated HTML documents are valid nor will it validate against a reference.
It will merely fail on:
- broken example code
- Sphinx build errors
Building the docs on CircleCI required adding about 400 megabytes of latex packages.
It's probably better to add them to the Docker container in the future. This probably requires a custom one though.

Test if sphinx build is succesful

---

pyfar/dsp/interpolation.py
tests/test_dsp_resample.py

Closes #328 
add aliasing suppression to resample function. To see this in action, e.g., use
```python
import pyfar as pf
signal = pf.signals.noise(512, seed=7)
true = pf.dsp.resample(signal, 48000, suppress_aliasing=True)
false = pf.dsp.resample(signal, 48000, suppress_aliasing=False)
pf.plot.time_freq(false, label="false")
ax = pf.plot.time_freq(true, label="true")
ax[1].legend()
```

add aliasing suppression to resample function

---

tests/test_deprecations.py
tests/test_plot.py
tests/test_plot_interaction.py

Use `create_figure()` from the testing module to specify the plot backend and limit figure size

Specify the plot backend in deprecation tests

---

pyfar/dsp/dsp.py
tests/test_dsp_deconvolution.py

Calling `deconvolve` without a `freq_range` argument leads to an error in `regularized_spectrum_inversion`, because `freq_range` is mandatory. I've added a mechanism for setting a default value.

add `freq_range` kwarg to `deconvolve`

---

pyfar/_concepts/audio_classes.py
pyfar/classes/audio.py
pyfar/dsp/dsp.py
tests/test_dsp_average.py

As discussed in the weekly
- add `cshape` and `caxis` to audio class concepts
- add caxis to `dsp.average` and `matrix_multiplication`

Introduce caxis to concepts and functions

---

pyfar/dsp/dsp.py
tests/test_deprecations.py
tests/test_dsp_pad_zeros.py

- Modi "before" and "after" are called "beginning" and "end" now. 
- Wrote PendingDeprecationWarning, that modi "before" and "after" can no longer be used in Pyfar Version 0.6.0. 
- PendingDeprecationWarning was ignored by default, so I used 'warnings.simplefilter('always')' to show the warning when modi "before" and "after" will be used. Is there a way to activate PendingDeprecationWarning permanent without using this line everytime?
- Insert 'test_pad_zero_modi' into test_deprecations.py

zero padding descriptors

---

pyfar/classes/coordinates.py
tests/test_coordinates.py

The tuple returned by `Coordinates.find_slice` can not be used to index multi-dimensional coordinates objects.
Sorry for the confusion. The return argument has to be a tuple, not an array. Otherwise it can not be used to assess multi-dimensional coordinates.
- fixed return argument
- added tests

Fix return arguments in Coordinates.find_slice

---

pyfar/dsp/filter/audiofilter.py

Closes #392
Revised docstring to clarify that the characteristic frequency of the shelve filter in modes ``I`` and ``II`` can only be set if the absolute value of the gain is sufficiently large. Documentation build locally with sphinx looks ok to me.
**documentation**, **dsp**

392 Unexpected Gain using high shelve filter with shelve type I and II

---

pyfar/classes/audio.py
tests/test_deprecations.py

Closes #412 
- deprecate `len(Signal)`
- test deprecation

Deprecate len(Signal)

---

pyfar/io/io.py
tests/test_io.py

Closes #411 
- Convert integer-valued sampling rates to int if they are of type float
- Raise an informal error for foat-valued sampling rates
- Update docstring
- Update testing

Write audio with different sampling rates types

---

pyfar/dsp/dsp.py
tests/test_dsp_normalize.py

- `dsp.find_impulse_response_start` still used `numpy.int`, which has been removed from numpy
- the test for `dsp.normalize` failed because the test tolerance was to low
- used `int` instead of `numpy.int` in `dsp.find_impulse_response_start`
- add test tolerance in `tests/test_dsp_normalize.py`

Fix bugs and failing test caused by numpy update

---

docs/conf.py
requirements_dev.txt

Use MathJax instead of the imgmath Sphinx extension. Works with recent Sphinx versions, so no need to limit to versions prior to v5.3.
This also generates nice vector font equations instead of rasterized images with quite low resolution.
See https://pyfar.readthedocs.io/en/bugfix-sphinx_math/ for the generated docs.
Closes #408, requires #409

Use MathJax instead of imgmath in docs

---

tests/test_audio_signal.py
tests/test_imports.py

Fixes the following warnings raised during testing
```
tests/test_audio_signal.py::test_magic_len
C:\Users\panik\Documents\Code\Python\pyfar\pyfar\pyfar\classes\audio.py:827: PyfarDeprecationWarning: 'len(Signal) will be deprecated in pyfar 0.8.0 Use Signal.n_samples instead'
warnings.warn(
tests/test_imports.py::test_import_pyfar
C:\Users\panik\anaconda3\envs\pyfar\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but tests/test_imports.py::test_import_pyfar returned [<module 'pyfar' from 'C:\\Users\\panik\\Documents\\Code\\Python\\pyfar\\pyfar\\pyfar\\__init__.py'>], which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
tests/test_imports.py::test_import_classes
.audio.Signal'>, <class …
```

Fix warnings in tests

---

pyfar/classes/audio.py
tests/test_io.py

Closes #442
-  `Signal._decode` always assumed time domain data. So we added
```python
obj_dict['_domain'],
obj_dict['_fft_norm']
```
- Signals initialized `self._n_bins = data.shape[-1]` if `domain =='freq'`, but it was never used.
- parametrized test for read and write a Signal

Reading frequency domain signals

---

pyfar/dsp/interpolation.py
tests/test_dsp_interpolation.py

`dsp.InterpolateSpectrum` resulted in Signals containing NaN values if interpolating on a log. frequency axis. The problem was caused by passing two identical frequencies to the interpolation object. This is now fixed by a better choice for f=0 Hz, which has to be treated because log(0) = -inf. The fix is required because NaN's are not allowed anymore (#435).
- calculate log. frequencies based on an arbitrary equidistant frequency scale starting at 1 not 0 to avoid log(0). This required to move code from the class initialization to the interpolation stage, because the new algorithm needs to know the number of frequency bins to which it interpolates.
- update tests
Is a cherry-pick of PR #436

Hotfix: Spectrum interpolation on logarithmic frequency axis avoiding zero frequency.

---

pyfar/_concepts/plots.py
pyfar/plot/line.py
pyfar/plot/two_d.py
tests/test_plot.py

Closes #400
- Expanded docstring to  pass an empty dictonary ``style = {}`` to use the current active plotstyle.
- Implemented Test

Empty dicts to use current active plotstyle

---

pyfar/dsp/interpolation.py

Fix legend of InterpolateSpectrum's show function

---

pyfar/plot/_line.py
pyfar/plot/_two_d.py
tests/test_plot.py

Closes #71
- Disable the minor tick labels for log axis to remove the unwanted tick labels.

Remove unwanted minor tick label for log plots

---

pyfar/dsp/dsp.py

The order of the parameters was different in the function header and docstring.
- Fix order of parameters in docstring

Fix order of parameters in docstring of dsp.normalize

---

pyfar/signals/stochastic.py

fix typo in pyfar.signals.noise

fix typo in pyfar.signals.noise

---

docs/concepts/resources/plot_shortcuts.rst
pyfar/utils.py
tests/test_utils.py

Closes #
- Add a concatenation function, concatenating Signals along specified channels.
- Add broadcasting parameter, which broadcasts the signals into largest cdim and a common shape, ignoring caxis. 
Otherwise approved

Add concatenate function

---

pyfar/classes/coordinates.py
pyfar/dsp/dsp.py
pyfar/plot/_utils.py
tests/test_dsp.py
tests/test_plot_interaction.py

latest flake8 version throws new errors:
```
pyfar/classes/coordinates.py:1742:64: E231 missing whitespace after ','
pyfar/classes/coordinates.py:1982:57: E231 missing whitespace after ','
pyfar/classes/coordinates.py:2358:71: E231 missing whitespace after ','
pyfar/classes/coordinates.py:2496:42: E231 missing whitespace after ','
pyfar/dsp/dsp.py:1976:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
pyfar/dsp/dsp.py:2212:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
pyfar/dsp/dsp.py:2216:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
pyfar/plot/_utils.py:201:12: E721 do not compare types, for exact checks use …
```

fix flake 8

---

tests/test_copy.py

Tests on CircleCI are failing due to faulty test implementations.
Replace the copy test for the abstract class Filter with tests for the subclasses

Replace tests for Filter with non-abstract class stubs

---

pyfar/classes/coordinates.py
tests/test_coordinates.py

first Coordinates.show just allow a mask, since we dont support masks for the find functions (#478) anymore we allow indexes as well.

allow indices for Coordinates.show

---

pyfar/dsp/interpolation.py

Adds a missing parameter to the docstring. My suggestion would be to also accept `'seconds'` as a unit.

[fractional_time_shift] add missing arg to docstr

---

requirements_dev.txt
setup.py

Hotfix #496 still requires removing the tight_layout module from pyfar after this
- fix Matplotlib dependency

tmporarily fix matplotlib version

---

docs/conf.py
examples/pyfar_demo.ipynb
pyfar/classes/coordinates.py
pyfar/samplings/samplings.py
pyfar/samplings/spatial.py
tests/test_deprecations.py

As discussed earlier we want to shift the samplings to spharpy. therefore we deprecate it now.
https://github.com/pyfar/spharpy/pull/33

Samplings deprecation and shift to spharpy

---

pyfar/signals/files.py

Closes #517, requires #519 
- Update for new `pyfar.Coordinates` class to avoid deprecation warnings
- Updating tests not required. Everything tested in `tests/test_signals_files.py`

Fix deprecation warnings in `pyfar.signals.files.head_related_impulse_responses`

---

pyfar/classes/coordinates.py
pyfar/signals/files.py
tests/test_coordinates_find.py

- Fix typo in docstring and code: Rename distance measure `spherical_radiance` to `spherical_radians`
- Fix assertion for distance measure: Rename `spherical_degree` to `spherical_radians`
- Fix computation of spherical distance meausres
- Add tests for spherical distance measures

Hot fixes for `pyfar.Coordinates.find_nearest`

---

pyfar/signals/deterministic.py

Improve documentation for paramter `sweep_rate`

Improve docstring for pyfar.signals.exponential_sweep_time

---

examples/pyfar_demo.ipynb

Closes #390, i.e., plots don't show up in the [current](https://mybinder.org/v2/gh/pyfar/pyfar/main?filepath=examples%2Fpyfar_demo.ipynb) examples notebook on binder, which can be fixed if explicitly setting the Matplotlib backend to `inline` as done in the [suggested](https://mybinder.org/v2/gh/pyfar/pyfar/bug/plots_in_example_notebook?filepath=examples%2Fpyfar_demo.ipynb) examples notebook
- explicitly set Matplotlib backend

Fix plots not showing in examples notebook

---

pyfar/classes/audio.py
tests/test_audio_frequency_data.py
tests/test_audio_signal.py
tests/test_audio_time_data.py

This PR adds a `transpose` method to all `Signals`, very similar to `np.ndarray.transpose`.

add transpose method to _Audio

---

pyfar/classes/audio.py
tests/test_audio_signal.py

- check the fft normalization in complex setter
- throw error if complex flag is to be set and fft norm is `rms`

add check for fft_norm in complex setter

---

pyfar/utils.py
tests/test_utils.py

Fix bug in concatenate channels

---

pyfar/classes/coordinates.py

This has been broken for a while now. 
The code in the scatter and quiver plots looks like it should be re-done, so I've implemented this as a hot-fix inside the show method. Eventually I'd suggest merging with the scatter function in spharpy.
- Fixes the equal axes scaling issue mentioned in PR #364 
- Returns the Axis object as mentioned in the docstring
``` python 
import pyfar as pf
s = pf.samplings.sph_gaussian(10)
s.show()
```

Make Coordiantes.show() use equal axes scaling and return Axis object.

---

pyfar/_concepts/coordinates.py

replace old naming convention description

---

pyfar/classes/coordinates.py

change output from:
```
1D Coordinates object with 40 points of cshape (40,)
domain: cart, convention: right, unit: met
coordinates: x in meters, y in meters, z in meters
Does not contain sampling weights
```
to:
```
1D Coordinates object with 40 points of cshape (40,)
Does not contain sampling weights
```

remove obsolete information from print Coordinates

---

requirements_dev.txt
setup.py

Closes #501 
- Remove version restriction for Matplotlib

Remove restriction for matplotlib version

---

pyfar/dsp/fft.py
tests/test_fft.py

Closes #553: Contrary to their definitions, FFT normalizations 'power' and 'psd' retained the phase of the signal. I think its a leftover from before the 'signal.freq_raw' property was introduced in 0.4.0 (PR https://github.com/pyfar/pyfar/pull/274), when retaining the phase was required to correctly calculate the inverse.
- Changed squaring operation from `spec*np.abs(spec) `to `np.abs(spec)**2`
- Updated tests

Remove phase for FFT normalizations 'power' and 'psd'

---

pyfar/dsp/dsp.py
tests/test_dsp.py

Test find impulse response delay complex

---

pyfar/dsp/filter/__init__.py
pyfar/dsp/filter/_audiofilter.py
pyfar/dsp/filter/audiofilter.py
tests/test_filter.py

Wrapper function for allpass implementation #527 
I probably should add a test for the filter properties to ``test_filter.py``. Any ideas for a smart way of checking if the filter is doing what it's supposed to do?
Link to docs:
https://pyfar--571.org.readthedocs.build/en/571/modules/pyfar.dsp.filter.html#pyfar.dsp.filter.allpass

Wrapper function for private 1st and 2nd order allpass implementations

---

pyfar/classes/coordinates.py

- ```coords.sh_order = None``` was not working

hotfix: allow None in sh_order setter

---

pyfar/classes/coordinates.py

Docstring for coordinates properties are now identical with the table introduced in #591. Note that this includes a couple of small fixes where coordinate names were confused after copy/past mistakes and correcting the coordinate ranges from < to \leq if required.

Fix math and description of coordinates

---

pyfar/classes/coordinates.py
tests/test_coordinates_find.py

There was a bug when converting the spherical distance measures to eucledian distance.
- Fixed the bug
- Updated and improved the tests to be correct and tests spherical distance measures for multiple radii

Fix bug in `Coordinates.find within`

---

pyfar/classes/audio.py
tests/test_audio_signal_arithmetic.py

Closes #587 
- Bypass rules for fft norm if only one audio object is involved in the opeeration
- Add and update tests
- Update docstrings
I discovered that we had a test that explicitly does not allow `1/signal` if the FFT norm is not `'none'`. I did not remove this test yet. Do we want to stay hard?

Relax arithmetic rules in case only one audio object is involved

---

pyfar/classes/orientations.py
pyfar/dsp/dsp.py

- tests are failing atm
- remove attributes for init, since init is not supposed the get called directly.
- add **kwargs to make it wok with [scipy's](https://github.com/scipy/scipy/releases/tag/v1.14.0) new parameter scalar-first (it is also backwardcompatible)
- change from ``'Hz'`` parameter in [scipy](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.signal.remez.html)
also general remark: we can discuss if its a good idea to overwrite the init function, just to allow to run 'pf.Orientations()' even if the orientation is not empty, beacuse scipy does not allow it.

include kwargs to parse to scipy in to support the new parameter.

---

docs/index.rst

replaces the no_title in previous 
add header to index so that the previous page on pyfar.html 
points to be discussed.
- rename readme header from pyfar to readme
old version see at the end of the page: https://pyfar.readthedocs.io/en/latest/pyfar.html
fixed version: https://pyfar--637.org.readthedocs.build/en/637/pyfar.html

add header to index

---

pyfar/classes/coordinates.py
tests/test_coordinates_find.py

Closes #616 
Added a radius tolerance ``radius_tol`` parameter to ``Coordinates.find_nearest`` in case the differences between the radii are larger than zero when using spherical distance measures.

Introduce radius_tol to Coordiantes.find_nearest()

---

docs/classes/pyfar.audio.rst
docs/classes/pyfar.orientations.rst
pyfar/classes/audio.py
pyfar/classes/orientations.py

Some classes still used an explicit documentation of their magic methods, which I think is not good practive.
closes #506 
- Move documentation of `Orientation.__init__` to the class docstring and make interactive links
- Move documentation from Audio objects (Signal/TimeData/FrequencyData) `__init__` to the class docstring.
- Move Information from Audio objects `__getitem__`, `__setitem__`, and `__iter__` to the module dosctring.
In the latter case, we might consider adding an example notebook to the gallery instead. The information in the docs on this is rather sparse. But I did not want to add stuff in this pull.

Harmonize class documentation

---

README.rst

Link to SoundFile docs in README is deprecated.
[https://pysoundfile.readthedocs.io](https://pysoundfile.readthedocs.io) leads to a 404 page, as pysoundfile was renamed to soundfile. The docs are now located at [https://python-soundfile.readthedocs.io/](https://python-soundfile.readthedocs.io/).

Updated link to the SoundFile docs

---

pyfar/plot/ticker.py
pyfar/samplings/spatial.py

fix deprecation warnings on main to avoid sth like #638 in future
requires #638
we could think about a test on circle ci which breaks if we get deprecation warnings:
```
pytest tests -W error::DeprecationWarning
```

fix deprecation warnings from matplotlib and numpy

---

pyfar/classes/filter.py
tests/test_filter.py
tests/test_filter_classes.py
tests/test_fractional_octaves.py

I changed the squeeze in ``Filter.process`` so it doesn't squeeze any of the input signal's channel dimensions.
Closes #627 
I would do separate PRs for gammatone class and the dsp-functions if changes are necessary.

Change squeeze in filter class to keep cshape of input signal

---

pyfar/classes/audio.py
tests/test_audio_frequency_data.py
tests/test_audio_signal.py
tests/test_audio_time_data.py
tests/test_filter_classes.py

Disable getting specific samples or frequencies from a signal through slicing

---

.circleci/config.yml
README.md
setup.py

End support for Python 3.8 as discussed during the weekly and required by #682

deprecate Python 3.8

---

pyfar/classes/coordinates.py
pyfar/dsp/filter/_audiofilter.py

Creating a Coordinates object always raises a warning, even in featres scheduled for deprecation are *not* used.
Change the way the warning for the deprecated `sh` property of the class is raised.

Remove unwanted warning in Coordinates initialization

---

pyfar/plot/line.py
pyfar/plot/two_d.py

Missing whitespace between ``'left'`` and "to"in docstring of new ``side`` parameter caused a rendering issue.

Complex signals: fix ``side`` docstring

---

pyfar/plot/_two_d.py

The unit was not plotted to the colorbar when using `unit='auto'`

Fix unit string in group delay plot

---

pyfar/io/io.py
tests/test_io.py

Closes #706
- fix usage of compress parameter in ``pyfar.io.write``
- add test whether the compressed file is smaller then the uncompressed one.

hot: fix compress flag in pyfar.io.write

---

pyfar/io/io.py

verbose was always True since it was not possible to change it when sf.read_sofa is called interanally.
Maybe we can make it in this releae ^^

add verbose to read_sofa

---

pyfar/signals/files.py

Supress irrelevant command line output when reading sofa files.
There was a notification for custom fields when loading headphone impulse responses. However, the custom fields are not used nor returned. I hence disabeled it there, and everywhere else, where it might occur in the future.

Improve pyfar.signals.files

---

pyfar/dsp/__init__.py
pyfar/dsp/dsp.py
pyfar/signals/deterministic.py
tests/test_dsp_correlate.py

@sikersten maybe you remember our discusion from I while ago: I now figured that `scipy.signal.correlate` can perform only linear correlation. This function can perform cyclic correlation in addition, which was required in the case which we discussed a while ago.

Add corrleation function to pyfar.dsp

---

pyfar/signals/files.py
tests/test_signals_files.py

Technically not a bug, because it was mentioned in the docs - but unessesarily complicated.
- Make `pyfar.signals.files.head_related_impulse_responses` work with array likes and pyfar Coordinate objects

Enhance head-related impulse responses

---

pyfar/dsp/dsp.py
tests/test_dsp_normalize.py

Closes #721 
- use square root of a signals energy and power for normalization
- use square root of target as well.
- update docs and tests

Normaliztation: Force energetic properties to match the target after normalization

---

pyfar/dsp/filter/fractional_octaves.py
tests/test_deprecations.py

deprecate `frequencies` return in `reconstructing_fractional_octave_bands()`
Closes #657

deprecate 'frequencies' reconstructing_fractional_octave_bands()

---

pyfar/dsp/filter/fractional_octaves.py
tests/test_fractional_octaves.py

return exact results for octave and third octave for limits out of range.
bug:
```
pf.dsp.filter.fractional_octave_frequencies(
num_fractions=3, frequency_range=[20000, 96000])
```
returns
```
(array([20000.]), array([19952.62314969]))
```
is now fixed. if frequency_range is not in the standard range, just the exact solution is returned.

return exact results for octave and third octave for limits out of range

---

pyfar/classes/filter.py
tests/test_filter_classes.py

Technically a bug, but I assume this function is rarely used. Make it a bug or release with the next features?
- Add missing default in `pyfar.FilterIIR.init_state`
- Test default value
- Implement and test raising an error for invalud values

Add missing default in `pyfar.FilterIIR.init_state`

---

pyfar/classes/filter.py
tests/test_filter_classes.py

Closes #730
Applying a FIR filter takes very long for larger signals, because  scipy's `lfilter` uses `np.convolve` (direct convolution) which in most cases is much slower than overlapp-add or fft convolution.
Changes proposed:
Have `FIRFilter.process` use scipy's `oaconvole`

Use oaconvolve for FIR process

---

pyfar/classes/filter.py
tests/test_filter_classes.py

Closes #766 
- Add `impulse_response_length` method to all class functions. This is a port of [impzlength](https://de.mathworks.com/help/signal/ref/impzlength.html). These methods are tested against values computed with `impzlength`.
- Use new method to set default impulse response length for all filter classes
- Raise a warning if user values for impulse response length are smaller than the estimated length

Impulse response length estimation for Filter objects

---

docs/_static/custom.js
docs/conf.py

Closes #785 
Adjust display of secondary sidebar using custom js.
Show only class `attribute` in sidebar instead of `class.attribute`.

Fix secondary sidebar display of class attributes

---

pyfar/dsp/fft.py

- make the style of the docstring constistant
- follows the Contribution guidelines now

fix inconstistant docstring format

---

docs/conf.py

With the current level it's required to always go back to the main API docs page to change to a different sub-module or sub-page.
These can now be navigated using the left hand side-bar.

Increase TOC depth for left sidebar to 2

---

pyfar/classes/coordinates.py

Which issue(s) does this pull request close?
This might be related to https://github.com/pyfar/spharpy/pull/121/files.
The problem is that if additional checks are required by subclasses (e.g. SamplingSphere), the _set_points need to be reimplemented, which causes duplicate code. This can be overcome by moving the input checks into a dedicaded method whichout setting the result.
replaces #803 this merges into main intendent as a patch release
- '_set_points' is still doing the same as before
- introduce '_check_points', which performs the input checks and broadcasting to the arrays.
- '_set_points' is calling '_check_points' before setting the points

Patch: Coordinates._set_points: separate internal checks from setting the variables

---

pyfar/constants/constants.py
tests/test_constants_air_attenuation.py

kind of followed from the discussion in #825
- no decible values are allowed in FrequencyData
- return decible values ``alpha`` as a numpy array instead of FrequencyData

BUG: return decible air attenuation as numpy array

---

pyfar/dsp/dsp.py
tests/test_dsp_average.py

An error occurred in `dsp.average` when an integer value was passed for `caxis` and the corresponding axis had only one channel.
- force iterable to avoid the error
- expand tests

fix bug in case caxis is not iteratable
